import { Manrope } from 'next/font/google'
import "./globals.css";
import PrelineScript from "@/components/PrelineScript";
import NavBar from "@/components/Nav/nav";


const monrope = Manrope({
  weight: ['400', '800'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monrope.className} bg-firstRow-A1 max-w-[1600px] mx-auto`}>
        <PrelineScript />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
